In [2]:
import numpy as np #importing the numpy library and given alias name as np

to check the version of the numpy library

In [3]:
print(np.__version__)

1.21.5


to check the dimensions of the array

In [5]:
a = np.array([[[12]]])
print(a.ndim)

3


to get the dimensions of the numpy without using the print function

In [6]:
a = np.array([[[[1,2]]]])
a.ndim

4

to set the dimension of the array as you want we use the ndmin attribute

In [12]:
a = np.array([12,23,24] , ndmin=5)
print(a)
print(a.ndim)

[[[[[12 23 24]]]]]
5


to make a 3D array

In [24]:
a = np.array([[(1,2,3),(4,5,6)],[(4,8,9),(56,75,31)]], dtype=tuple)
print(a)
a.ndim

[[[1 2 3]
  [4 5 6]]

 [[4 8 9]
  [56 75 31]]]


3

converting a list, tuple or dictionary into an array

In [27]:
z = (12,34,43)
print(type(z))
a = np.array(z)
print(a)
print(type(a))
print(type(z))
x = [12,23,454]
print(type(x))
y = np.array(x)
print(y)
print(type(y))
print(x)
print(type(x)) #original do not change

<class 'tuple'>
[12 34 43]
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'list'>
[ 12  23 454]
<class 'numpy.ndarray'>
[12, 23, 454]
<class 'list'>


convertng dictionary into an array

In [28]:
b = {"Ram" :1 , "Shyam" : 2}
print(type(b))
a = np.array(b)
print(a)
print(type(a))
print(type(b))

<class 'dict'>
{'Ram': 1, 'Shyam': 2}
<class 'numpy.ndarray'>
<class 'dict'>
